// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	GetUsers(ctx context.Context) ([]User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
